name: deploy
inputs:
  environment:
    required: true
  port:
    required: true
runs:
  using: composite
  steps:
    - name: echo 
      run: echo Deployment to ${{inputs.environment}} has started
      shell: cmd
    - name: clone
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: deploy
    - name: delete
      run: |
        $env:RUNNER_TRACKING_ID=""
        pm2 delete greetings-app-${{inputs.environment}} & EXIT /B 0
      shell: powershell
      working-directory: deploy
    - name: start
      run: pm2 start app.py --name greetings-app-${{inputs.environment}} -- --port ${{inputs.port}}
      shell: cmd
      working-directory: deploy