name: deploy
inputs:
  environment:
    required: true
  port:
    required: true
runs:
  using: composite
  steps:
    - name: echo 
      run: echo Deployment to ${{inputs.environment}} has started
      shell: cmd
    - name: clone
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: deploy
    - name: delete
      run: RUNNER_TRACKING_ID="" && pm2 delete greetings-app-${{inputs.environment}} & EXIT /B 0
      shell: cmd
      working-directory: deploy
    - name: start
      run:  pm2 start app.py --no-daemon --name greetings-app-${{inputs.environment}} -- --port ${{inputs.port}}
      shell: cmd
      working-directory: deploy
    - name: check if app is running
      run: pm2 list
      shell: cmd
      working-directory: deploy